# Generated by Django 5.1 on 2024-08-08 18:20

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_ticket_reservation_alter_reservation_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=theatre.models.create_custom_path
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=theatre.models.create_custom_path
            ),
        ),
    ]
