# Generated by Django 5.1 on 2024-08-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_actor_image_play_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="theatrehall",
            options={"verbose_name_plural": "theatre halls"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["play", "theatre_hall"],
                name="theatre_per_play_id_f2894b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["show_time"], name="theatre_per_show_ti_6fef99_idx"
            ),
        ),
    ]
