# Generated by Django 5.1 on 2024-08-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0006_ticket_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["id"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]
