# Generated by Django 5.1 on 2024-08-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0007_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
